apiVersion: v1
kind: Pod
metadata:
  name: myredis-app
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: redis:alpine
      ports:
        - containerPort: 6379
          name: redis