apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          args: ["--protected-mode", "no", "--appendonly", "yes"]
          ports:
            - containerPort: 6379
              name: redis
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 3
            periodSeconds: 5
