apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      env: nginx
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        tier: frontend

    spec:
      containers:
        - name: nginx-pod
          image: nginx
